<?php

 /* 
  * Implement hook_init()
  */
function current_date_init() {
  $is_current_date_enabled = variable_get('enable_current_date', 0);
  $message_type = variable_get('message_type',0);;
      
  if($is_current_date_enabled == 1){
    $date  = t('Today is ' . date('l, F d, Y'));
    switch ($message_type){
      case '0' : { $message_type = 'status'; break;}
      case '1' : { $message_type = 'warning'; break;}
      case '2' : { $message_type = 'error'; break;}
    }
    drupal_set_message($date,$message_type);  
  }
}

/*
 * Implement hook_menu()
 */
function current_date_menu(){
  $items['admin/config/current-date'] = array(
    'title' => t('Current Date Page'),
    'description' => 'Show message with current date',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('current_date_from'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/*
 * Callback  for current date
 */
function current_date_from($form){
  $form['enable_current_date'] = array(
      '#type' => 'checkbox', 
      '#title' => t('Enable current date message'),
      '#default_value' => variable_get('enable_current_date', false),
  );
  
  $type = array(
      0 => t('Status'),
      1 => t('Warning'), 
      2 => t('Error'),
  );
   $form['message_type'] = array(
      '#type' => 'radios',
      '#title' => t('Message Type'),
      '#options' => $type,      
      '#default_value' => isset($node->type) ? $node->type : 0,      
  );
   
  return system_settings_form($form);
}
/*
 * Implements hook_modulea_config() for test purpose.
 */
function current_date_modulea_config(){
  return t('This text comes from module current_date.<br>');
}